### ISSUE TITLE
Incorrect `PYTHONPATH` when using `from` in `packages`

### ISSUE THREAD

**Issue by nfantone** [python-poetry/install.python-poetry.org#138]
I'll admit, right off the bat, that I'm not sure what the expected behaviour here is or what exactly is causing my issues, so apologies up front if I'm off.

Regardless, here's what I see.

I have a project that I'm migrating from [a flat structure to a `src` layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). In its current state, it looks like this:

```
my-project/
├── project/
│   ├── __init__.py
│   ├── package/
│   │   ├── __init__.py
│   │   └── ...
│   └── module.py
├── tests/
│   ├── __init__.py
│   └─── package/
│        ├── __init__.py
│        └── test_package.py
├── plugins/
│   ├── __init__.py
│   └── commitizen.py
├── pyproject.toml
└── README.md
```

```toml
# pyproject.toml

[tool.poetry]
name = "my-project"
version = "0.1.0"
packages = [{ include = "project" }]

[tool.poetry.plugins."commitizen.plugin"]
# References plugins top level package
cz_jira_conventional = "plugins.commitizen:JiraConventionalCz"
```

This installs fine and allows me to execute binaries such as:

```sh
poetry run cz --help
poetry run pytest .
# etc.
```

However, after changing my layout to use `src/` and updating `pyproject.toml` `packages` accordingly, those commands above stop working, raising errors related to missing modules.

```
my-project/
├── src/
│   └── project/
│       ├── __init__.py
│       ├── package/
│       │   ├── __init__.py
│       │   └── ...
│       └── module.py
├── tests/
│   ├── __init__.py
│   └── package/
│       ├── __init__.py
│       └── test_package.py
├── plugins/
│   ├── __init__.py
│   └── commitizen.py
├── pyproject.toml
└── README.md
```

Note that only sources under `project` moved locations. Everything else, including `plugins/` and `tests/` stayed the same.

```toml
# pyproject.toml

[tool.poetry]
name = "my-project"
version = "0.1.0"
packages = [{ include = "project", from = "src" }]
```

Which results in:

```sh
poetry run cz --help
Traceback (most recent call last):
# ...
ModuleNotFoundError: No module named 'plugins'
```

```sh
poetry run pytest .
tests/test_package.py:5: in <module>
    from tests.factories import (
E   ModuleNotFoundError: No module named 'tests'
```

I found two ways to work around this:

1. Append `PYTHONPATH=.` to all `poetry run` commands (from project's root).
2. Add `{ include = "plugins" }, { include = "tests" }` to the `packages` in `pyproject.toml` (and re-run `poetry install`).

But none of them seem like things I should really be doing or caring about — I certainly didn't need to before.

Could you help me understand what exactly is going on? Am I misusing something?
